project:
  output-dir: ./docs/en


website:

#General Webside Design
  reader-mode: true
  back-to-top-navigation: true
  page-footer:
    background: lightgrey
    left: "Copyright 2023, Thomas Gross"
    right:
      - icon: github
        href: https://github.com/
      
      
  
#Webside Organisation
  title: "Tools for NRM"
  navbar:
    background: dark
    left:
      - text: "MFA"
        file: Lektion0_1_Lernziele.qmd
      - text: "About"
        file: about.qmd
      - text: "Home" 
        file: index.qmd
    right:
      - href: ../de
        text: Deutsch
      - href: ../en
        text: English

  sidebar:
    - titel: "Lessons"
      style: "docked"
      background: info
      contents:
      - section: "Overview"
        contents:
          - Lektion0_1_Lernziele.qmd
          - Lektion0_2_Software.qmd
          - Lektion0_3_FAQ.qmd
      - section: "Introduction"
        contents:
          - Lektion1_1_Grundlagen.qmd
          - Lektion1_2_LBD.qmd
          - Lektion1_3_Workshop.qmd
      - section: "Mathematical modelling"
        contents:
          - Lektion2_1_Bilanzierung.qmd
          - Lektion2_2_LBD.qmd
          - Lektion2_3_Workshop.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    minimal: false

editor: visual




