project:
  type: website
  output-dir: docs

website:

#General Webside Design
  reader-mode: true
  back-to-top-navigation: true
  page-footer:
    background: lightgrey
    left: "Copyright 2023, Thomas Gross"
    right:
      - icon: github
        href: https://github.com/
      
      
  
#Webside Organisation
  title: "Tools für NRM"
  navbar:
    background: dark
    left:
      - text: "MFA"
        file: Lektion0_1_Lernziele.qmd
      - text: "About"
        file: about.qmd
      - text: "Home" 
        file: index.qmd

  sidebar:
    - titel: "Lektionen"
      style: "docked"
      background: info
      contents:
      - section: "Überblick"
        contents:
          - Lektion0_1_Lernziele.qmd
          - Lektion0_2_Software.qmd
          - Lektion0_3_Bewertung.qmd
          - Lektion0_4_FAQ.qmd
      - section: "Einführung"
        contents:
          - Lektion1_1_Grundlagen.qmd
          - Lektion1_2_LBD.qmd
          - Lektion1_3_Workshop.qmd
      - section: "Bilanzierung"
        contents:
          - Lektion2_1_Bilanzierung.qmd
          - Lektion2_2_LBD.qmd
          - Lektion2_3_Workshop.qmd


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual




