project:
  output-dir: ./docs


website:

#General Webside Design
  reader-mode: true
  back-to-top-navigation: true
  page-footer:
    background: lightgrey
    left: "Copyright 2023, Thomas Gross"
    right:
      - icon: github
        href: https://github.com/
      
      
  
#Webside Organisation
  title: "Tools für NRM"
  navbar:
    background: dark
    left:
      - text: "MFA"
        file: Lektion0_1_Lernziele.qmd
      - text: "About"
        file: about.qmd
      - text: "Home" 
        file: index.qmd
    right:
      - href: https://thomasgrossfhnw.github.io/MFA
        text: Deutsch
      - href: https://thomasgrossfhnw.github.io/MFA/en
        text: English

  sidebar:
    - titel: "Lektionen"
      style: "docked"
      background: info
      contents:
      - section: "Überblick"
        contents:
          - href: Lektion0_1_Lernziele.qmd
            text: Lernziele
          - href: Lektion0_2_Software.qmd
            text: Software
          - href: Lektion0_3_FAQ.qmd
            text: FAQ
      - section: "Einführung"
        contents:
          - href: Lektion1_1_Grundlagen.qmd
            text: Grundlagen
          - href: Lektion1_2_LBD.qmd
            text: Learning by doing
          - href: Lektion1_3_Workshop.qmd
            text: Workshop
      - section: "Bilanzierung"
        contents:
          - href: Lektion2_1_Bilanzierung.qmd
            text: Bilanzierung
          - href: Lektion2_2_LBD.qmd
            text: Learning by doing
          - href: Lektion2_3_Workshop.qmd
            text: Workshop

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    minimal: false

editor: visual




